apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-conf
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}

data:
  envoy.yaml: |
    admin:
      # access_log_path: /dev/stdout
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9090
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
          - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  access_log:
                    - name: envoy.access_loggers.file
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: "/dev/stdout" # easier debugging
                  codec_type: AUTO
                  stat_prefix: ingress_https
                  upgrade_configs:
                   - upgrade_type: websocket
                  route_config:
                    name: local_route
                    virtual_hosts:
                        - name: reverse_proxy
                          domains: ["*"]
                          routes:
                            - match: # Call to / goes to the landing page
                                path: "/"
                              route: { cluster: web }
                            - match: # Web IDE lives in this path
                                prefix: "/ide"
                              route: { cluster: web }
                            - match: # JS API lives in this path
                                prefix: "/jsapi"
                              route: { cluster: web }
                            - match: # Notebook file storage at this path
                                prefix: "/notebooks"
                              route: { cluster: web }
                            - match: # Any GRPC call is assumed to be forwarded to the real service
                                prefix: "/"
                              route:
                                cluster: grpc-api
                                max_stream_duration:
                                  grpc_timeout_header_max: 0s
                                timeout: 0s
                  http_filters:
                    - name: envoy.filters.http.health_check
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                        pass_through_mode: false
                        headers:
                          - name: ":path"
                            exact_match: "/healthz"
                          - name: "x-envoy-livenessprobe"
                            exact_match: "healthz"
                    - name: envoy.filters.http.grpc_web
                    - name: envoy.filters.http.router
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                common_tls_context:
                  alpn_protocols: ["h2"]
                  tls_certificates:
                    - certificate_chain:
                        filename: /etc/ssl/tls.crt
                      private_key:
                        filename: /etc/ssl/tls.key
      clusters:
        - name: grpc-api
          connect_timeout: 10s
          type: LOGICAL_DNS
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: grpc-api
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          # address: grpc-api # here we assume the name of the websocket proxy
                          address: 127.0.0.1
                          port_value: 8888
        #      health_checks:
        #        timeout: 1s
        #        interval: 10s
        #        unhealthy_threshold: 2
        #        healthy_threshold: 2
        #        grpc_health_check: { }
        - name: web
          connect_timeout: 10s
          type: LOGICAL_DNS
          lb_policy: ROUND_ROBIN
          http_protocol_options: {}
          load_assignment:
            cluster_name: web
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      hostname: web
                      address:
                        socket_address:
                          # address: web
                          address: 127.0.0.1
                          port_value: 8080