version: "3.4"

services:
  deephaven:
    image: ghcr.io/deephaven/server-tensorflow:latest
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
      - 6006:6006
    volumes:
      - ./data:/data
    environment:
      - JAVA_OPTS=-Xmx4g

  examples:
    image: ghcr.io/deephaven/examples
    volumes:
      - ./data:/data
    command: initialize
