name: Long Check CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'main', 'check/**', 'release/v*' ]
    tags: [ 'v*' ]

jobs:
  long-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # note: this uses Zulu and not AdoptOpenJDK or other. should make sure we build and test on the same one...
      - name: Setup JDK
        id: setup-java
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'zulu'
          java-version: '8.0.302'

      - name: Setup gradle properties
        run: |
          cat .github/env/${{ runner.os }}/gradle.properties >> gradle.properties
          echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties

      - name: Check
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: long-checks
          arguments: --scan --continue check
          gradle-version: wrapper

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: long-check-ci-results
          path: '**/build/test-results/*/TEST-*.xml'

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: long-check-ci-reports
          path: '**/build/reports/tests/**'