name: Quick CI

on:
  pull_request:
    branches: [ 'main', 'rc/v*' ]
  push:
    branches: [ 'main', 'check/**', 'release/v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      non-docs: ${{ steps.filter.outputs.non-docs }}
    steps:
      # Must checkout for push, but not pull_request according to the action
      - name: Checkout
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v5
      - name: Check for non-docs changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            non-docs:
              - '!docs/**'

  quick:
    runs-on: ubuntu-24.04
    needs: changes
    if: ${{ needs.changes.outputs.non-docs == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check gitignore rules
        run: .github/scripts/check-gitignore-rules.sh

      - name: Setup JDK 11
        id: setup-java-11
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java-11.outputs.path }}" >> $GITHUB_ENV

      - name: Setup gradle properties
        run: |
          .github/scripts/gradle-properties.sh >> gradle.properties
          cat gradle.properties

      - name: Quick Task
        # Even though quick includes spotlessCheck, we want to make sure it runs first and fails ASAP for quick feedback
        run: ./gradlew --scan spotlessCheck quick

      - name: Upload JVM Error Logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: quick-ci-jvm-err
          path: '**/*_pid*.log'
          if-no-files-found: ignore

  verify-python-min-version:
    runs-on: ubuntu-24.04
    needs: changes
    if: ${{ needs.changes.outputs.non-docs == 'true' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install vermin
        run: pip install vermin==1.6.0

      - name: Verify minimum version support
        run: vermin -t=3.9 --no-tips --eval-annotations --violations --feature fstring-self-doc --feature union-types --exclude-regex '\.pyi$' py/server/deephaven py/client py/client-ticking py/embedded-server
